In [1]:
import numpy as np
from PIL import Image
from tqdm import tqdm
import os

image_dir = 'images/'

images_mean_rgb_array = []
for image_file in tqdm(os.listdir(image_dir)):
    image_array = np.array(Image.open(image_dir + image_file))
    image_mean_rgb = np.mean(image_array, axis=(0, 1))
    images_mean_rgb_array.append(image_mean_rgb)
    
images_mean_rgb_array

100%|██████████| 9/9 [00:00<00:00, 29.74it/s]


[array([108.83830967, 109.65480358,  84.62809254, 255.        ]),
 array([106.76403567, 115.6533544 , 102.58610513, 255.        ]),
 array([ 57.65280143,  53.714362  ,  48.34544711, 255.        ]),
 array([114.34808462, 115.02601224, 102.04647436, 255.        ]),
 array([114.4254814 , 124.22387419, 112.04268934, 255.        ]),
 array([ 62.12955322,  57.67031773,  50.9376854 , 255.        ]),
 array([ 84.96260877,  93.12494265,  83.83141749, 255.        ]),
 array([ 80.22999304,  88.79467582,  78.8620891 , 255.        ]),
 array([ 82.81920692,  79.16497199,  69.66060278, 255.        ])]

In [2]:
np.mean(images_mean_rgb_array, axis=0)

array([ 90.24111941,  93.00303495,  81.43784481, 255.        ])